### Obtener todos los equipo
GET http://localhost:3000/api/equipo

### Obtener un equipo por id
GET http://localhost:3000/api/equipo/1

### Crear un equipo
POST http://localhost:3000/api/equipo
Content-Type: application/json

{
    "nombre": "Audi",
    "jefedeequipo": "Andreas Seidl",
    "presidente": "Markus Duesmann",
    "pais": "Alemania",
    "campeonatosdepilotosganados": 0,
    "campeonatosdeconstructoresganados": 0,
    "campeonatoscorridos": 0,
    "fechadefundacion": "2026-01-01",
    "logo": "logo_audi.png"
}

### Actualizar un equipo
PUT http://localhost:3000/api/equipo/1
Content-Type: application/json

{
    "jefedeequipo": "Andreas Seidl",
    "presidente": "Markus Duesmann",
    "campeonatosdepilotosganados": 0,
    "campeonatosdeconstructoresganados": 0,
    "campeonatoscorridos": 0,
    "logo": "logo_audi.png"
}

### Eliminar un equipo
DELETE http://localhost:3000/api/equipo/1
